// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ArchLens.Upload.Tests.BDD.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class UploadDeDiagramaFeature : object, Xunit.IClassFixture<UploadDeDiagramaFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Upload de Diagrama", "  Como um usuário do sistema\n  Eu quero fazer upload de diagramas de arquitetura\n" +
                "  Para que eles sejam processados e analisados", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Upload.feature"
#line hidden
        
        public UploadDeDiagramaFeature(UploadDeDiagramaFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            await this.TestInitializeAsync();
        }
        
        async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload de arquivo PNG válido")]
        [Xunit.TraitAttribute("FeatureTitle", "Upload de Diagrama")]
        [Xunit.TraitAttribute("Description", "Upload de arquivo PNG válido")]
        public async System.Threading.Tasks.Task UploadDeArquivoPNGValido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload de arquivo PNG válido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
    await testRunner.GivenAsync("que eu tenho um arquivo PNG válido chamado \"diagram.png\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.WhenAsync("eu envio o upload do arquivo para \"/diagrams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 10
    await testRunner.ThenAsync("a resposta deve ter status code 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 11
    await testRunner.AndAsync("a resposta deve conter o campo \"diagramId\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter o campo \"status\" com valor \"Received\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload de arquivo JPG válido")]
        [Xunit.TraitAttribute("FeatureTitle", "Upload de Diagrama")]
        [Xunit.TraitAttribute("Description", "Upload de arquivo JPG válido")]
        public async System.Threading.Tasks.Task UploadDeArquivoJPGValido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload de arquivo JPG válido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que eu tenho um arquivo JPG válido chamado \"architecture.jpg\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("eu envio o upload do arquivo para \"/diagrams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta deve ter status code 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 18
    await testRunner.AndAsync("a resposta deve conter o campo \"fileName\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload de arquivo com extensão não suportada")]
        [Xunit.TraitAttribute("FeatureTitle", "Upload de Diagrama")]
        [Xunit.TraitAttribute("Description", "Upload de arquivo com extensão não suportada")]
        public async System.Threading.Tasks.Task UploadDeArquivoComExtensaoNaoSuportada()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload de arquivo com extensão não suportada", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
    await testRunner.GivenAsync("que eu tenho um arquivo com extensão não suportada chamado \"doc.txt\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 22
    await testRunner.WhenAsync("eu envio o upload do arquivo para \"/diagrams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 23
    await testRunner.ThenAsync("a resposta deve ter status code 415", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload de arquivo com assinatura inválida")]
        [Xunit.TraitAttribute("FeatureTitle", "Upload de Diagrama")]
        [Xunit.TraitAttribute("Description", "Upload de arquivo com assinatura inválida")]
        public async System.Threading.Tasks.Task UploadDeArquivoComAssinaturaInvalida()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload de arquivo com assinatura inválida", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 25
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
    await testRunner.GivenAsync("que eu tenho um arquivo com assinatura inválida chamado \"fake.png\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 27
    await testRunner.WhenAsync("eu envio o upload do arquivo para \"/diagrams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 28
    await testRunner.ThenAsync("a resposta deve ter status code 415", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Upload de arquivo duplicado retorna o existente")]
        [Xunit.TraitAttribute("FeatureTitle", "Upload de Diagrama")]
        [Xunit.TraitAttribute("Description", "Upload de arquivo duplicado retorna o existente")]
        public async System.Threading.Tasks.Task UploadDeArquivoDuplicadoRetornaOExistente()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Upload de arquivo duplicado retorna o existente", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 30
  this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 31
    await testRunner.GivenAsync("que eu tenho um arquivo PNG válido chamado \"duplicate.png\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 32
    await testRunner.AndAsync("que eu já fiz upload desse arquivo anteriormente", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 33
    await testRunner.WhenAsync("eu envio o upload do arquivo para \"/diagrams\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 34
    await testRunner.ThenAsync("a resposta deve ter status code 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 35
    await testRunner.AndAsync("a resposta deve conter o campo \"isDuplicate\" com valor \"True\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await UploadDeDiagramaFeature.FeatureSetupAsync();
            }
            
            async System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await UploadDeDiagramaFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
